### ISSUE TITLE
Link field overrides Kirby's toLink method

### ISSUE THREAD

**Issue by gerricom** [OblikStudio/kirby-link-field#11]
As discussed at Slack yesterday I figured that this plugin overrides Kirby's own `toLink` method. 

As `toLink` is an appropriate name for this method, it would be very nice, if one could call the original method, if the field is not a link-field.

Another solution would be to rename the method of the plugin...

**Comment by hdodov** [comment]
It seems to me that there are two solutions:

1. Change the plugin's method name
2. Invoke the default `toLink()` method when the field value is not in YAML format

Having two link methods could be confusing, so I personally prefer the second approach, which would function like this:

1. Field value is parsed with `$field->yaml()`
2. If the result is an associative array with a `type` value, leave it as is
3. Otherwise, invoke the default `toLink()` method

This would make the transition from default `toLink()` to the plugin's `toLink()` very smooth because it would require no changes in the template. You simply change the blueprint, open the panel, change the data, and save it. The old value would now be YAML and the plugin functionality will kick in.

**Comment by hdodov** [comment]
✅

**Comment by hdodov** [comment]
✅
